name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: ['1.22','1.21', '1.20']
        platform: [ubuntu-latest] # can not run in windows OS
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v3
    - name: Test
      run: go test -v -cover .
